language: node_js
node_js:
  - 4.2
deploy:
  provider: heroku
  api_key: 
    secure: "nYwDuKiHHklRS5J2MCWNYDwe1Ay2Pz516guH1dtyhKBmgqnoH6dTaBdFn2dj/MNxmG2IVh5K9bnyUMBtSpm6+yTaIQVqrlUJ8PHgXjh66P1ACOGfJefARo/VEh0qH4zOJkmrP4IgwKWZd1iMsjQSujQQZa3IievHu4YaD7T6eR0yNkYhdWfRXgx7OX2xQNGE1EC8Mdypnra1A8ohC6vDCaRoLSlWlV9+AOnOwjZy2Jkup7PaxQ3go7CMwn6sqOco5+o5Vui8x7irf6oZ7pYnv0JLgVuqvfXA73jGymTgj44tw5pVFwiXIFeZcNaTOk+qHQfWC/KU6TZNcJEosEvpFaX9w+7noeeVoEOSepSVQE3f8DY+nFpBcejLsPlLF90oGr8Z+Z1Who9gvM+pxCzmwIS8qMvLh2i4Zuv8W+MoYVDnAeph2vjy60bw1jvJYAznalfYVt2rEF4OGMidnliTH6PTuBQwWHle/0uvHG5DduZEoK++LOovX44ko9lFn91/QNtTz2gksu9zAFZJixwS9ZosZmNaywY7FbhfMcYrf4Xal08aRigHm4xqqE/jRTzicHVZkbK1zlevwO74rtP8ym1l9xOhbIo0IStGV2/C2KFToKkrr5pWkPo/LaJPkjwnB2n64NHWb7QcejAgFDuPUEoAzm4NzlaFvFfZY0XkLx0="     
  app: api-weather-custom
script:
  - mocha test/controllers



